// <auto-generated />
namespace Scribe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial_database_build : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_database_build));
        
        string IMigrationMetadata.Id
        {
            get { return "201809260237437_initial_database_build"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
